services:

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - ~/data/db_data:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 172.18.0.4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "172.18.0.4"]
      interval: 3s
      timeout: 2s
      retries: 10
    env_file:
      - .env

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile 
    volumes:
      - ~/data/wordpress_data:/var/www/html
    networks:
      inception:
        ipv4_address: 172.18.0.2
    env_file:
      - .env

  nginx:
    depends_on:
      mariadb:
        condition: service_healthy
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ~/data/wordpress_data:/var/www/html
    networks: 
      inception:
        ipv4_address: 172.18.0.3
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:443 | grep 'WordPress'"]
      interval: 8s
      timeout: 6s
      retries: 10

  wait-for-nginx:
    build: 
      context: ./requirements/tools/wait-for-nginx
    depends_on:
      nginx:
        condition: service_healthy

volumes:
  wordpress_data:
  db_data:

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
