services:

  mariadb:
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    build:
      context: ./srcs/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./srcs/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    extra_hosts:
      - "jganivet.42.fr:192.168.1.1"

  nginx:
    depends_on:
      mariadb:
        condition: service_healthy
    build: 
      context: ./srcs/nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    extra_hosts:
      - "jganivet.42.fr:192.168.1.2"
      
volumes:
  wordpress_data:

networks:
  inception:
    driver: bridge