services:

  mariadb:
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
        ipv4_address: 172.18.0.4
    build:
      context: ./srcs/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 2s
      retries: 10
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./srcs/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
        ipv4_address: 172.18.0.2
    env_file:
      - .env

  nginx:
    depends_on:
      mariadb:
        condition: service_healthy
    build: 
      context: ./srcs/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
        ipv4_address: 172.18.0.3
    env_file:
      - .env

volumes:
  wordpress_data:

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16