version: '3'

services:
  wordpress:
    build:
      context: ./srcs/wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    networks:
      - inception

  mariadb:
    build:
      context: ./srcs/mariadb
    ports:
      - "3306:3306"
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    build: 
      context: ./srcs/nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  wordpress_data:

networks:
  inception:
    driver: bridge