services:

  mariadb:
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    build:
      context: ./srcs/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./srcs/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  nginx:
    depends_on:
      - wordpress
    build: 
      context: ./srcs/nginx
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress_data:

networks:
  inception:
    driver: bridge